SELECT HALF.FLAVOR
	FROM FIRST_HALF AS HALF
    INNER JOIN ICECREAM_INFO AS INFO
    	ON HALF.FLAVOR=INFO.FLAVOR
    WHERE HALF.TOTAL_ORDER > 3000
    	AND INGREDIENT_TYPE='fruit_based'
    ORDER BY TOTAL_ORDER DESC;
